### ISSUE TITLE
"Notify me when Lime 1.0 is released" option

### ISSUE THREAD

**Issue by lenntt** [limetext/support#4]
I found out about the Limetext project only today and I hope to use it one day (as I experience the same uncertanties and lack of communications with ST), while admitting ashamedly I won't contribute much as a developer. I guess I'm just one of those end-users.

Therefore I would be interested in having a **mailing list, facebook post, or whatever media that's already in my system of checking frequently, once Limetext is '1.0'**.

I there anything like that yet for potential end-users?

**Comment by zoli** [comment]
We have a [blog](http://limetext.org/blog/) which also has [rss feed](http://limetext.org/blog/rss.xml) you can subscribe to the feed.We will announce there probably on any releases.
