### ISSUE TITLE
Release date ??

### ISSUE THREAD

**Issue by yuvarajvemula** [limetext/support#6]
I am waiting to see lime text in my system for long time.. I am not computer expert.. So I can only install it on when it properly officially released.. So I egarly waiting to install it on computer.. So can you say when the 1st stable release may available.. When it will be ready to ship (approximately) ..?? Sorry for if my English is bad

**Comment by f2l2pe** [comment]
Hello @shivarajnaidu , by the actual situation of the project it has pretty much stopped, some discussion is occuring on gitter but unfortunately a release date ,even an aproximmate one, can't be set.

**Comment by yuvarajvemula** [comment]
Stopped !! Why ??

**Comment by erbridge** [comment]
The project has no financial backing, so it relies on the availability of its developers and community to work on it. So it will be ready when it's ready.

**Comment by jspizziri** [comment]
@erbridge 

I have similarly been watching this project for quite some time. In regards to a release date, is the project roadmap and the v0.1 milestones I see in each repository up to date?

I'd be interested in learning what the situation is there from the perspective of being able to contribute. I've been using [Atom](https://atom.io/) for a while, but have been looking forward to a compiled option as Atom can sometimes have poor performance when dealing with large files/datasets.

In your estimation, what's the percent completion in regards to a v0.1 or v0.1-alpha release?

**Comment by erbridge** [comment]
We are currently focusing on the QML frontend, and @zoli's made a decent amount of progress in backend recently. The goal of v0.1 is to have a functioning text editor with enough features that we can work on Lime Text using Lime Text. This probably means an incomplete plugin API, and a limited set of features, but it should be usable.

As for the milestones and roadmap, I expect they are out of date (or missing for some packages), though any help triaging issues would be appreciated.

**Comment by zoli** [comment]
Just to mention I made the v0.1 goals simpler and we are tracking it here https://github.com/limetext/lime-qml/issues/28.

**Comment by yuvarajvemula** [comment]
I have tried atom Editor .. But I felt it's very bad when comes to performance perspective.. On the other hand sublime text ,it's awesome ,but not open source.. That's why I am waiting to see lime Editor in action ..
