### ISSUE TITLE
lime-qml: Buffer.qml:1 module "QtQuick" version 2.5 is not installed

### ISSUE THREAD

**Issue by rgson** [limetext/support#7]
I've been trying to set up the development environment to hopefully be able to contribute a bit to the project, but I'm having some issues with the build process.

I've downloaded the backend and the qml frontend following the build instructions for Ubuntu 14.04 (I'm actually on Linux Mint 17.3, but it's based on Ubuntu 14.04). Both backend and frontend pass all tests. However, when attempting to run the built `main` for the frontend, I get the following error, hindering startup:

```
[04/24/16 02:21:34] [EROR] file:////home/robin/code/go/src/github.com/limetext/lime-qml/main/qml/Window.qml.:265 Type View unavailable
file:////home/robin/code/go/src/github.com/limetext/lime-qml/main/qml/View.qml:69 Type Buffer unavailable
file:////home/robin/code/go/src/github.com/limetext/lime-qml/main/qml/Buffer.qml:1 module "QtQuick" version 2.5 is not installed
```

The error message is rather straight forward. Problem is, I've installed all the Qt packages listed in the build instructions and then some. I tried scouring the internet for similar issues and found some for older versions (QtQuick 2.0 and 2.1, both of which seem to work fine for me). The suggested solutions all pointed me back to the packages I've already installed or to `ubuntu-sdk`, which I also tried to no avail.

If anyone who has got the build up and running (preferably on a Ubuntu-based system) could share the list of installed Qt packages, that'd be ace. Any other ideas of what to try are also very welcome, of course.

If I manage to get the build working, I'll start by creating some build instructions or even an automated build script for Linux Mint 17.3 and possibly update the one for Ubuntu 14.04 if needed.

**Comment by erbridge** [comment]
Try grabbing the packages used by travis from https://github.com/limetext/lime-qml/blob/master/.travis.yml.

**Comment by rgson** [comment]
Thanks for the advice. All of those packages were already installed and up-to-date, though. I added the ubuntu-sdk-team repo and did a dist-upgrade just to be sure. Unfortunately, the issue persists.

I'll try setting up a fresh Ubuntu VM to see if I can get it working there. My system is already a pretty fresh install, but perhaps there's still something interfering with Qt somehow.

**Comment by rgson** [comment]
It works fine with the listed packages on a fresh install of Ubuntu 16.04, meaning it's either something local to my system or it's something with Linux Mint 17.3. With the upcoming release of Mint 18 it should soon be a non-issue either way.
